name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy app
        uses: easingthemes/ssh-deploy@v2.2.2
        with:
          server: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/martin/servers/test
            bash restartNginxServer.sh